### ISSUE TITLE
Issue with stems

### ISSUE THREAD

**Issue by Monniasza** [CemraJC/stenotoppers#12]
The stems in StenoToppers are fragile, unlike mass produced keycaps. I've alredy broken several keycaps due to this flaw
![keycap comparison](https://github.com/CemraJC/stenotoppers/assets/37037712/6267b28c-a8fc-4ee9-892e-fd6cdba7ce48)

On the top is a mass produced Strike Battle Spectra keycap, on the bottom a StenoTopper. Notice how the StenoTopper does not cover the switch stem fully, but the default keycaps do.

**Comment by CemraJC** [comment]
Unfortunately that's a limitation of the design - there's as much plastic in there as possible, but if there was any more (or a surrounds) then it makes the walls too thin and they're difficult to print. 

3D printers have gotten a lot better than when the keycaps were originally designed, so potentially reducing the layer height and using PETG could help? If you or someone else can come up with a design that manages to make a slot surrounds (a la OEM keycap) and still fit the tolerance of the manufacturing process, then I'll happily merge a PR for it!
