### ISSUE TITLE
Generate smaller STL files that will print faster?

### ISSUE THREAD

**Issue by ddrscott** [CemraJC/stenotoppers#2]
Is it possible to generate smaller sets of STI files? My local library has a 6 hour print maximum.
Maybe group by left and and right and final?
I don't have Autodesk Inventor to attempt it myself.

Thanks

**Comment by CemraJC** [comment]
Fear not! You do not need AutoDesk Inventor to do this.

As you are aware, there are individual STL files provided for each type of keycap. If, I assume, you want to be sending two print jobs to the printer to stay under the 6 hour maximum, then I would recommend using software such as [AutoDesk Meshmixer](http://www.meshmixer.com/download.html) or [meshlab](http://www.meshlab.net/) to merge the single-keycap STLs into each job as you desire.

As this is quite a specific scenario, hopefully you can understand why I would like you to do this yourself. In short order, I will add a section to the Readme with my above comments, for future users.
