### ISSUE TITLE
Low profile stenotopper models

### ISSUE THREAD

**Issue by Pomegranate123** [CemraJC/stenotoppers#5]
Hey, I'm not sure if this project is still active as of now, but maybe these files could be added to the repo? 
I wanted to install stenotoppers on my low profile mech keyboard, which has gateron low profile switches with a different connection than the standard mx stems, so I modified the models to work with my keyboard (they should also work with khail low profile switches and maybe others I'm unaware of). I'll drop the files in here if anyone needs them. I'll also include the freecad file I used if anyone wants to modify it more.

[stenotoppers_lowprofile.zip](https://github.com/CemraJC/stenotoppers/files/5354840/stenotoppers_lowprofile.zip)

![lp-stenotoppers](https://user-images.githubusercontent.com/59014624/95581460-617e1a80-0a39-11eb-958a-48bbe88658de.jpg)

**Comment by CemraJC** [comment]
Thanks for the contribution!! 

I'll add these to the main repository, they look great.
